" dotfiles
" https://github.com/garybunofsky/dotfiles

" plugins
source ~/dotfiles/vim/plugins.vim
source ~/dotfiles/vim/plugins/ale.vim
source ~/dotfiles/vim/plugins/ctrlp.vim
source ~/dotfiles/vim/plugins/lightline.vim
source ~/dotfiles/vim/plugins/indentguides.vim

" vim
source ~/dotfiles/vim/formatting.vim
source ~/dotfiles/vim/input.vim
source ~/dotfiles/vim/line-numbers.vim
source ~/dotfiles/vim/netrw.vim
source ~/dotfiles/vim/search.vim
source ~/dotfiles/vim/theme.vim
source ~/dotfiles/vim/whitespace.vim

set visualbell
