source ~/.oh-my-zsh/custom/plugins/antigen/antigen.zsh
source ~/.oh-my-zsh/custom/plugins/zsh-nvm/zsh-nvm.plugin.zsh

source ~/dotfiles/zsh/alias
source ~/dotfiles/zsh/functions
source ~/dotfiles/zsh/antigen
source ~/dotfiles/zsh/paths

export EDITOR=vim
